### ISSUE TITLE
importing session

### ISSUE THREAD

**Issue by bendichter** [datajoint/element-session#14]
Using the latest master for this repo:

```python
from element_session.session import Session
```

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_794/2689618127.py in <module>
----> 1 from element_session.session import Session

ModuleNotFoundError: No module named 'element_session.session'
```

It looks like this was changed 7 days ago, with [this commit](https://github.com/datajoint/element-session/commit/9a1dc0c3436600723c1de94414fabd1229256e78). I'm not really sure what issue that fix was addressing, but this import was working for me before and now it's not. This does work, however:

```python
from element_session.session_with_datetime import Session
```

**Comment by kabilar** [comment]
Thanks @bendichter.  Ah yes, this update was introduced in #12 and further details can be found in this [comment](https://github.com/datajoint/element-session/pull/12#issuecomment-1035281997).

Your solution works.  As the [__init__.py](https://github.com/datajoint/element-session/blob/main/element_session/__init__.py) ensures that the `session_with_datetime` module is default, you could also use the following: 

```python
from element_session import session
session.Session()
```

If a user wanted to use the session schema with an integer value as the primary attribute (instead of a datetime):

```python
from element_session import session_with_id as session
session.Session()
```

**Comment by bendichter** [comment]
@kabilar ok, if that is the intended behavior I am happy to make the appropriate changes in my PRs
